#!/usr/bin/env python

from sys import argv
from os.path import basename
from uuid import uuid4

assert len(argv) > 1

for arg in argv[1:]:
    filename = basename(arg)
    var = filename.upper().replace(".","_")
    var += "_" + str(uuid4()).upper().replace("-","_")

    with open(arg) as f:
        contents = f.read()

    with open(arg,"w") as f:
        f.write("#ifndef {}\n".format(var))
        f.write("#define {}\n\n".format(var))
        f.write(contents)
        f.write("\n#endif")
